"""initial schema: users, user_settings, projects, project_data, ai_usage_daily

Revision ID: 4534e7ff60ea
Revises: 
Create Date: 2026-08-07 10:35:57.484715

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = '4534e7ff60ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_usage_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_ai_usage_user_date')
    )
    with op.batch_alter_table('ai_usage_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_daily_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ig_access_token', app.models.EncryptedText(), nullable=True),
    sa.Column('ig_user_id', sa.String(length=64), nullable=True),
    sa.Column('ig_username', sa.String(length=255), nullable=True),
    sa.Column('ig_token_obtained_at', sa.String(length=64), nullable=True),
    sa.Column('ig_token_expires_at', sa.String(length=64), nullable=True),
    sa.Column('ads_account_id', sa.String(length=64), nullable=True),
    sa.Column('account_niche', sa.Text(), nullable=True),
    sa.Column('anthropic_api_key', app.models.EncryptedText(), nullable=True),
    sa.Column('anthropic_key_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anthropic_api_key', app.models.EncryptedText(), nullable=True),
    sa.Column('anthropic_key_verified', sa.Boolean(), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('max_media', sa.Integer(), nullable=False),
    sa.Column('content_language', sa.String(length=8), nullable=False),
    sa.Column('whisper_model', sa.String(length=16), nullable=False),
    sa.Column('daily_report_hour', sa.Integer(), nullable=False),
    sa.Column('auto_refresh_interval_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('project_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_project_data_project_key')
    )
    with op.batch_alter_table('project_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_data_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_data_project_id'))

    op.drop_table('project_data')
    op.drop_table('user_settings')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('ai_usage_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_daily_user_id'))

    op.drop_table('ai_usage_daily')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
